// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUajwI34KfI7ucQlSDB_mOOiG0DFkG4gw',
    appId: '1:389683139486:web:ba9b5931598d3689f1bc8f',
    messagingSenderId: '389683139486',
    projectId: 'artfolio-6e6ad',
    authDomain: 'artfolio-6e6ad.firebaseapp.com',
    storageBucket: 'artfolio-6e6ad.appspot.com',
    measurementId: 'G-T15EDSJPTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zmKQmPWBAiSwynDQRsusGPQGe-X0QpE',
    appId: '1:389683139486:android:7a0c0120094b946ff1bc8f',
    messagingSenderId: '389683139486',
    projectId: 'artfolio-6e6ad',
    storageBucket: 'artfolio-6e6ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXoyVswfZVtMR9dCLxMK0GAjiiC4GS-I',
    appId: '1:389683139486:ios:269f7ec11b325cb9f1bc8f',
    messagingSenderId: '389683139486',
    projectId: 'artfolio-6e6ad',
    storageBucket: 'artfolio-6e6ad.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXoyVswfZVtMR9dCLxMK0GAjiiC4GS-I',
    appId: '1:389683139486:ios:269f7ec11b325cb9f1bc8f',
    messagingSenderId: '389683139486',
    projectId: 'artfolio-6e6ad',
    storageBucket: 'artfolio-6e6ad.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUajwI34KfI7ucQlSDB_mOOiG0DFkG4gw',
    appId: '1:389683139486:web:16fa5a2f81b2a021f1bc8f',
    messagingSenderId: '389683139486',
    projectId: 'artfolio-6e6ad',
    authDomain: 'artfolio-6e6ad.firebaseapp.com',
    storageBucket: 'artfolio-6e6ad.appspot.com',
    measurementId: 'G-BBLC7SN8NY',
  );
}
